import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatShortTime } from "./useDashboardData";

function downloadAttendancePdf({
  attendanceList,
  totalEmployees,
  presentCount,
  absentCount,
  getEmployeeName,
}) {
  if (attendanceList.length === 0) {
    alert(
      "No attendance data available for today."
    );
    return;
  }

  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const today = new Date();
  const day = String(today.getDate()).padStart(
    2,
    "0"
  );
  const month = String(
    today.getMonth() + 1
  ).padStart(2, "0");
  const year = today.getFullYear();

  const formattedDate = `${day}/${month}/${year}`;
  const fileDate = `${day}-${month}-${year}`;

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Shop Attendance System", 14, 15);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Today's Attendance Report",
    14,
    24
  );

  doc.setFontSize(10);
  doc.text(`Date: ${formattedDate}`, 14, 32);
  doc.text(
    `Total Employees: ${totalEmployees}`,
    80,
    32
  );
  doc.text(`Present: ${presentCount}`, 165, 32);
  doc.text(`Absent: ${absentCount}`, 220, 32);

  const tableData = attendanceList.map(
    (attendance, index) => {
      const punchIn = attendance.punchIn || {};
      const punchOut = attendance.punchOut || {};

      return [
        index + 1,
        getEmployeeName(attendance.mobileNumber),
        attendance.mobileNumber || "",
        attendance.date || formattedDate,
        formatShortTime(punchIn.timestamp),
        formatShortTime(punchOut.timestamp),
        attendance.status || "Punched In",
        punchIn.accuracy != null
          ? `${punchIn.accuracy} m`
          : "",
        punchOut.accuracy != null
          ? `${punchOut.accuracy} m`
          : "",
      ];
    }
  );

  autoTable(doc, {
    startY: 40,
    head: [
      [
        "Sr.",
        "Employee",
        "Mobile",
        "Date",
        "Punch In",
        "Punch Out",
        "Status",
        "In Accuracy",
        "Out Accuracy",
      ],
    ],
    body: tableData,
    theme: "grid",
    styles: {
      fontSize: 7,
      cellPadding: 2.5,
      valign: "middle",
    },
    headStyles: {
      fontSize: 7,
      fontStyle: "bold",
      halign: "center",
    },
    columnStyles: {
      0: { cellWidth: 12, halign: "center" },
      1: { cellWidth: 38 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 },
      6: { cellWidth: 30 },
      7: { cellWidth: 25 },
      8: { cellWidth: 25 },
    },
    margin: {
      left: 10,
      right: 10,
    },
  });

  const pageCount =
    doc.internal.getNumberOfPages();

  for (
    let page = 1;
    page <= pageCount;
    page++
  ) {
    doc.setPage(page);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Generated by Shop Attendance System",
      14,
      202
    );
    doc.text(
      `Page ${page} of ${pageCount}`,
      250,
      202
    );
  }

  doc.save(`Attendance-${fileDate}.pdf`);
}

export default downloadAttendancePdf;
